-- Per-job caps, sandbox minutes, spend ceiling, provider/cost on jobs.

ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "maxTokensPerJob" INTEGER NOT NULL DEFAULT 120000;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "maxFilesPerJob" INTEGER NOT NULL DEFAULT 60;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "maxOutputBytesPerJob" INTEGER NOT NULL DEFAULT 2000000;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "monthlySandboxMinutes" INTEGER NOT NULL DEFAULT 300;

ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "pauseReason" TEXT;
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "sandboxMinutesUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "monthlySpendLimitUsd" DECIMAL(12, 4);
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "spendUsd" DECIMAL(12, 4) NOT NULL DEFAULT 0;
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "spendAlert80Sent" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Project" ADD COLUMN IF NOT EXISTS "sandboxMeteredUntil" TIMESTAMP(3);

ALTER TABLE "GenerationJob" ADD COLUMN IF NOT EXISTS "estimatedCostUsd" DECIMAL(12, 6);
ALTER TABLE "GenerationJob" ADD COLUMN IF NOT EXISTS "provider" TEXT;
ALTER TABLE "GenerationJob" ADD COLUMN IF NOT EXISTS "model" TEXT;
ALTER TABLE "GenerationJob" ADD COLUMN IF NOT EXISTS "queuePosition" INTEGER;
